pipeline {
  agent any

  stages {
    stage('up') {
      steps {
        sh 'sudo docker-compose -f app1/docker-compose.yml up -d'
      }
    }
    stage('Test'){
      steps {
        sh 'sudo docker exec -d app1_identitest_1 /src/node_modules/protractor/bin/webdriver-manager start'
      },
      steps {
        sh 'sudo docker exec app1_identitest_1 /src/node_modules/protractor/bin/protractor /src/protractor/comf.js'
      }
    }
    stage('down'){
      steps {
        sh 'sudo docker-compose -f app1/docker-compose.yml down'
      }
    }
  }
}
