pipeline {
  agent any

  stages {
    stage('up') {
      steps {
        sh 'docker-compose -f app1/docker-compose.yml up -d'
      }
    }
    stage('Test'){
      steps {
        sh 'docker exec identitest ls -la'
      }
    }
    stage('down'){
      steps {
        sh 'docker-compose down'
      }
    }
  }
}
