pipeline {
  agent any

  stages {
    stage('up') {
      steps {
        sh 'sudo docker-compose -f app1/docker-compose.yml up -d'
      }
    }
    stage('Test'){
      steps {
        sh 'sudo docker exec app1_identitest_1 ls -la'
      }
    }
    stage('down'){
      steps {
        sh 'sudo docker-compose -f app1/docker-compose.yml down'
      }
    }
  }
}
